### ISSUE TITLE
change color button

### ISSUE THREAD

**Issue by alirezaseilsepor** [ohmae/color-chooser#4]
How can I change the color of the OK and Cancel buttons?

**Comment by ohmae** [comment]
The entity is AlertDialog, so please specify it in Theme.

**Comment by alirezaseilsepor** [comment]
I tried to change the color with the code snippet below, but I didn't succeed

    <style name="BaseThemeApp" parent="Theme.MaterialComponents.DayNight.NoActionBar">
        <item name="android:alertDialogTheme">@style/AlertDialogCustom</item>
    </style>
    
    <style name="AlertDialogCustom" parent="android:Theme.Material.Light.Dialog.Alert">
        <item name="android:colorPrimary">#00397F</item>
        <item name="android:colorAccent">#0AAEEF</item>
        <item name="buttonBarNegativeButtonStyle">@style/NegativeButtonStyle</item>
        <item name="buttonBarPositiveButtonStyle">@style/PositiveButtonStyle</item>
    </style>
    
    <style name="NegativeButtonStyle" parent="Widget.MaterialComponents.Button.TextButton.Dialog">
        <item name="android:textColor">#f00</item>
    </style>

    <style name="PositiveButtonStyle" parent="Widget.MaterialComponents.Button.TextButton.Dialog">
        <item name="android:textColor">#00f</item>
    </style>

**Comment by ohmae** [comment]
e.g.
```xml
<style name="AppTheme" parent="Theme.Material3.DynamicColors.DayNight">
    <item name="alertDialogTheme">@style/AppTheme.Dialog</item>
</style>
<style name="AppTheme.Dialog" parent="ThemeOverlay.Material3.Dialog.Alert">
    <item name="buttonBarPositiveButtonStyle">@style/AppTheme.Button.Positive</item>
    <item name="buttonBarNegativeButtonStyle">@style/AppTheme.Button.Negative</item>
</style>
<style name="AppTheme.Button.Positive" parent="Widget.Material3.Button.TextButton.Dialog">
    <item name="android:textColor">#00FF00</item>
</style>
<style name="AppTheme.Button.Negative" parent="Widget.Material3.Button.TextButton.Dialog">
    <item name="android:textColor">#FF0000</item>
</style>
```
![](https://github.com/ohmae/color-chooser/assets/7691979/b64a5984-6933-4a88-b379-2f2490e8acc0)

**Comment by alirezaseilsepor** [comment]
Thank you, it worked
